name: Multiple shells commands

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: python commands
        run: |
          python -c "import platform; print(platform.processor())"
  
  run-windows-command:
    runs-on: windows-latest
    needs:
      - run-shell-command
    steps:
      - name: current directory with powershell
        run: Get-Location
        shell: pwsh # Utiliser PowerShell sur Windows
      - name: print some default env variables
        run: |
          echo "HOME: $env:HOME"
          echo "GITHUB_WORKFLOW: $env:GITHUB_WORKFLOW"
          echo "GITHUB_ACTION: $env:GITHUB_ACTION"
          echo "GITHUB_ACTIONS: $env:GITHUB_ACTIONS"
